import type { User, Empleado, Recibo, Solicitud, Novedad, Evento, Ticket } from '@/types'

export const SECTORES = [
  'Dirección General',
  'Educación',
  'Programas Sociales',
  'Administración',
  'Comunicación',
  'Mantenimiento',
  'Salud Comunitaria',
  'Tecnología',
]

export const empleados: Empleado[] = [
  {
    id: '1',
    nombre: 'Administrador',
    apellido: 'RRHH',
    dni: '20.111.222',
    fechaNacimiento: '1980-06-15',
    email: 'admin@fno.org.ar',
    telefono: '299-4100001',
    direccion: 'Av. Argentina 1000, Neuquén Capital',
    contactoEmergencia: { nombre: 'Laura Sánchez', telefono: '299-4200002', relacion: 'Esposa' },
    sector: 'Dirección General',
    cargo: 'Jefe de Recursos Humanos',
    fechaIngreso: '2015-03-01',
    tipoContrato: 'Planta Permanente',
    jornada: 'Full Time',
    supervisor: 'Directora Ejecutiva',
    estado: 'activo',
    diasVacaciones: 21,
    diasVacacionesUsados: 0,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=AR&backgroundColor=1e3a5f&fontColor=ffffff',
  },
  {
    id: '2',
    nombre: 'María',
    apellido: 'González',
    dni: '28.456.789',
    fechaNacimiento: '1985-03-22',
    email: 'mgonzalez@fno.org.ar',
    telefono: '299-4561234',
    direccion: 'Calle Mitre 456, Neuquén Capital',
    contactoEmergencia: { nombre: 'Carlos González', telefono: '299-4567891', relacion: 'Esposo' },
    sector: 'Educación',
    cargo: 'Directora de Escuela',
    fechaIngreso: '2018-03-01',
    tipoContrato: 'Planta Permanente',
    jornada: 'Full Time',
    supervisor: 'Dirección Ejecutiva',
    estado: 'activo',
    diasVacaciones: 21,
    diasVacacionesUsados: 7,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=MG&backgroundColor=3b73b8&fontColor=ffffff',
  },
  {
    id: '3',
    nombre: 'Juan',
    apellido: 'Pérez',
    dni: '31.234.567',
    fechaNacimiento: '1990-07-10',
    email: 'jperez@fno.org.ar',
    telefono: '299-4789012',
    direccion: 'Pasaje Las Flores 123, Neuquén',
    contactoEmergencia: { nombre: 'Ana Pérez', telefono: '299-4789013', relacion: 'Madre' },
    sector: 'Programas Sociales',
    cargo: 'Trabajador Social',
    fechaIngreso: '2020-06-15',
    tipoContrato: 'Contrato',
    jornada: 'Full Time',
    supervisor: 'María González',
    estado: 'activo',
    diasVacaciones: 14,
    diasVacacionesUsados: 14,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=JP&backgroundColor=5988c3&fontColor=ffffff',
  },
  {
    id: '4',
    nombre: 'Ana',
    apellido: 'Rodríguez',
    dni: '26.890.123',
    fechaNacimiento: '1983-11-05',
    email: 'arodriguez@fno.org.ar',
    telefono: '299-4321098',
    direccion: 'Av. Olascoaga 789, Neuquén',
    contactoEmergencia: { nombre: 'Pedro Rodríguez', telefono: '299-4321099', relacion: 'Hermano' },
    sector: 'Administración',
    cargo: 'Contadora',
    fechaIngreso: '2016-08-01',
    tipoContrato: 'Planta Permanente',
    jornada: 'Full Time',
    supervisor: 'Dirección Ejecutiva',
    estado: 'activo',
    diasVacaciones: 21,
    diasVacacionesUsados: 5,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=AR2&backgroundColor=2e5d9a&fontColor=ffffff',
  },
  {
    id: '5',
    nombre: 'Carlos',
    apellido: 'Martínez',
    dni: '33.456.789',
    fechaNacimiento: '1992-04-18',
    email: 'cmartinez@fno.org.ar',
    telefono: '299-4654321',
    direccion: 'Calle Roca 234, Plottier',
    contactoEmergencia: { nombre: 'Sofía Martínez', telefono: '299-4654322', relacion: 'Pareja' },
    sector: 'Tecnología',
    cargo: 'Técnico en Sistemas',
    fechaIngreso: '2022-01-10',
    tipoContrato: 'Contrato',
    jornada: 'Full Time',
    supervisor: 'Ana Rodríguez',
    estado: 'activo',
    diasVacaciones: 14,
    diasVacacionesUsados: 0,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=CM&backgroundColor=1e3a5f&fontColor=ffffff',
  },
  {
    id: '6',
    nombre: 'Laura',
    apellido: 'Fernández',
    dni: '29.567.890',
    fechaNacimiento: '1987-09-12',
    email: 'lfernandez@fno.org.ar',
    telefono: '299-4987654',
    direccion: 'Barrio Don Bosco 567, Neuquén',
    contactoEmergencia: { nombre: 'Roberto Fernández', telefono: '299-4987655', relacion: 'Padre' },
    sector: 'Salud Comunitaria',
    cargo: 'Enfermera',
    fechaIngreso: '2019-04-01',
    tipoContrato: 'Planta Provisional',
    jornada: 'Full Time',
    supervisor: 'Dirección Ejecutiva',
    estado: 'licencia',
    diasVacaciones: 21,
    diasVacacionesUsados: 10,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=LF&backgroundColor=3b73b8&fontColor=ffffff',
  },
  {
    id: '7',
    nombre: 'Roberto',
    apellido: 'Silva',
    dni: '25.678.901',
    fechaNacimiento: '1981-12-28',
    email: 'rsilva@fno.org.ar',
    telefono: '299-4876543',
    direccion: 'Av. San Martín 890, Neuquén',
    contactoEmergencia: { nombre: 'Marta Silva', telefono: '299-4876544', relacion: 'Esposa' },
    sector: 'Mantenimiento',
    cargo: 'Encargado de Mantenimiento',
    fechaIngreso: '2014-09-15',
    tipoContrato: 'Planta Permanente',
    jornada: 'Full Time',
    supervisor: 'Ana Rodríguez',
    estado: 'activo',
    diasVacaciones: 21,
    diasVacacionesUsados: 21,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=RS&backgroundColor=5988c3&fontColor=ffffff',
  },
  {
    id: '8',
    nombre: 'Valeria',
    apellido: 'López',
    dni: '35.123.456',
    fechaNacimiento: '1995-02-14',
    email: 'vlopez@fno.org.ar',
    telefono: '299-4543210',
    direccion: 'Calle Belgrano 321, Centenario',
    contactoEmergencia: { nombre: 'Claudia López', telefono: '299-4543211', relacion: 'Madre' },
    sector: 'Comunicación',
    cargo: 'Comunicadora Social',
    fechaIngreso: '2023-03-01',
    tipoContrato: 'Contrato',
    jornada: 'Part Time',
    supervisor: 'Dirección Ejecutiva',
    estado: 'activo',
    diasVacaciones: 14,
    diasVacacionesUsados: 0,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=VL&backgroundColor=2e5d9a&fontColor=ffffff',
  },
  {
    id: '9',
    nombre: 'Diego',
    apellido: 'Morales',
    dni: '30.987.654',
    fechaNacimiento: '1989-08-30',
    email: 'dmorales@fno.org.ar',
    telefono: '299-4210987',
    direccion: 'Pasaje Los Arrayanes 45, Neuquén',
    contactoEmergencia: { nombre: 'Patricia Morales', telefono: '299-4210988', relacion: 'Hermana' },
    sector: 'Educación',
    cargo: 'Docente',
    fechaIngreso: '2021-03-01',
    tipoContrato: 'Contrato',
    jornada: 'Part Time',
    supervisor: 'María González',
    estado: 'activo',
    diasVacaciones: 14,
    diasVacacionesUsados: 7,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=DM&backgroundColor=1e3a5f&fontColor=ffffff',
  },
  {
    id: '10',
    nombre: 'Gabriela',
    apellido: 'Torres',
    dni: '27.345.678',
    fechaNacimiento: '1984-05-20',
    email: 'gtorres@fno.org.ar',
    telefono: '299-4109876',
    direccion: 'Av. Independencia 678, Neuquén',
    contactoEmergencia: { nombre: 'Martín Torres', telefono: '299-4109877', relacion: 'Esposo' },
    sector: 'Programas Sociales',
    cargo: 'Coordinadora de Programas',
    fechaIngreso: '2017-07-01',
    tipoContrato: 'Planta Permanente',
    jornada: 'Full Time',
    supervisor: 'Dirección Ejecutiva',
    estado: 'vacaciones',
    diasVacaciones: 21,
    diasVacacionesUsados: 14,
    foto: 'https://api.dicebear.com/8.x/initials/svg?seed=GT&backgroundColor=3b73b8&fontColor=ffffff',
  },
]

export const users: User[] = [
  { id: 'u1', email: 'admin@fno.org.ar', password: 'admin123', role: 'admin', empleadoId: '1' },
  { id: 'u2', email: 'mgonzalez@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '2' },
  { id: 'u3', email: 'jperez@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '3' },
  { id: 'u4', email: 'arodriguez@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '4' },
  { id: 'u5', email: 'cmartinez@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '5' },
  { id: 'u6', email: 'lfernandez@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '6' },
  { id: 'u7', email: 'rsilva@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '7' },
  { id: 'u8', email: 'vlopez@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '8' },
  { id: 'u9', email: 'dmorales@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '9' },
  { id: 'u10', email: 'gtorres@fno.org.ar', password: 'empleado123', role: 'employee', empleadoId: '10' },
]

export const recibos: Recibo[] = [
  { id: 'r1', empleadoId: '2', mes: 4, anio: 2026, archivo: 'recibo_gonzalez_abr2026.pdf', fechaSubida: '2026-05-05', monto: 285000 },
  { id: 'r2', empleadoId: '2', mes: 3, anio: 2026, archivo: 'recibo_gonzalez_mar2026.pdf', fechaSubida: '2026-04-05', monto: 275000 },
  { id: 'r3', empleadoId: '2', mes: 2, anio: 2026, archivo: 'recibo_gonzalez_feb2026.pdf', fechaSubida: '2026-03-05', monto: 275000 },
  { id: 'r4', empleadoId: '2', mes: 1, anio: 2026, archivo: 'recibo_gonzalez_ene2026.pdf', fechaSubida: '2026-02-05', monto: 265000 },
  { id: 'r5', empleadoId: '3', mes: 4, anio: 2026, archivo: 'recibo_perez_abr2026.pdf', fechaSubida: '2026-05-05', monto: 195000 },
  { id: 'r6', empleadoId: '3', mes: 3, anio: 2026, archivo: 'recibo_perez_mar2026.pdf', fechaSubida: '2026-04-05', monto: 185000 },
  { id: 'r7', empleadoId: '4', mes: 4, anio: 2026, archivo: 'recibo_rodriguez_abr2026.pdf', fechaSubida: '2026-05-05', monto: 310000 },
  { id: 'r8', empleadoId: '4', mes: 3, anio: 2026, archivo: 'recibo_rodriguez_mar2026.pdf', fechaSubida: '2026-04-05', monto: 300000 },
  { id: 'r9', empleadoId: '5', mes: 4, anio: 2026, archivo: 'recibo_martinez_abr2026.pdf', fechaSubida: '2026-05-05', monto: 175000 },
  { id: 'r10', empleadoId: '6', mes: 4, anio: 2026, archivo: 'recibo_fernandez_abr2026.pdf', fechaSubida: '2026-05-05', monto: 220000 },
  { id: 'r11', empleadoId: '7', mes: 4, anio: 2026, archivo: 'recibo_silva_abr2026.pdf', fechaSubida: '2026-05-05', monto: 190000 },
  { id: 'r12', empleadoId: '8', mes: 4, anio: 2026, archivo: 'recibo_lopez_abr2026.pdf', fechaSubida: '2026-05-05', monto: 120000 },
  { id: 'r13', empleadoId: '9', mes: 4, anio: 2026, archivo: 'recibo_morales_abr2026.pdf', fechaSubida: '2026-05-05', monto: 155000 },
  { id: 'r14', empleadoId: '10', mes: 4, anio: 2026, archivo: 'recibo_torres_abr2026.pdf', fechaSubida: '2026-05-05', monto: 260000 },
  { id: 'r15', empleadoId: '1', mes: 4, anio: 2026, archivo: 'recibo_admin_abr2026.pdf', fechaSubida: '2026-05-05', monto: 350000 },
]

export const solicitudes: Solicitud[] = [
  {
    id: 's1', empleadoId: '3', tipo: 'permiso_personal',
    fechaInicio: '2026-05-26', fechaFin: '2026-05-26',
    descripcion: 'Necesito asistir a una consulta médica programada.',
    estado: 'pendiente', fechaCreacion: '2026-05-20',
  },
  {
    id: 's2', empleadoId: '9', tipo: 'llegada_tarde',
    fechaInicio: '2026-05-22',
    descripcion: 'Llegada tarde por turno odontológico. Aprox. 2 horas.',
    estado: 'pendiente', fechaCreacion: '2026-05-19',
  },
  {
    id: 's3', empleadoId: '5', tipo: 'vacaciones',
    fechaInicio: '2026-06-02', fechaFin: '2026-06-13',
    descripcion: 'Solicito período vacacional acordado previamente.',
    estado: 'aprobado', fechaCreacion: '2026-05-10',
    fechaResolucion: '2026-05-12',
    comentarioAdmin: 'Aprobado. Buen descanso.',
  },
  {
    id: 's4', empleadoId: '2', tipo: 'licencia_medica',
    fechaInicio: '2026-04-14', fechaFin: '2026-04-18',
    descripcion: 'Licencia por intervención quirúrgica programada. Adjunto certificado médico.',
    estado: 'aprobado', fechaCreacion: '2026-04-10',
    fechaResolucion: '2026-04-11',
    comentarioAdmin: 'Aprobado. Que te recuperes pronto.',
  },
  {
    id: 's5', empleadoId: '7', tipo: 'vacaciones',
    fechaInicio: '2026-05-01', fechaFin: '2026-05-21',
    descripcion: 'Período vacacional anual completo.',
    estado: 'aprobado', fechaCreacion: '2026-04-15',
    fechaResolucion: '2026-04-16',
  },
  {
    id: 's6', empleadoId: '8', tipo: 'pedido_administrativo',
    fechaInicio: '2026-05-21',
    descripcion: 'Solicito cambio de modalidad a teletrabajo los días viernes.',
    estado: 'rechazado', fechaCreacion: '2026-05-01',
    fechaResolucion: '2026-05-05',
    comentarioAdmin: 'Por el momento no es posible por requerimientos operativos.',
  },
  {
    id: 's7', empleadoId: '4', tipo: 'permiso_personal',
    fechaInicio: '2026-05-28', fechaFin: '2026-05-28',
    descripcion: 'Acto escolar del hijo. Solo medio día por la mañana.',
    estado: 'pendiente', fechaCreacion: '2026-05-20',
  },
]

export const novedades: Novedad[] = [
  {
    id: 'n1',
    titulo: '¡Feliz Día del Trabajador!',
    contenido: 'En este Día Internacional del Trabajador, la Fundación Neuquén Oeste quiere expresar su profundo agradecimiento a cada integrante de nuestro equipo. Su compromiso y dedicación son el motor que impulsa nuestra misión educativa y social. ¡Gracias por todo lo que hacen cada día!',
    categoria: 'novedad',
    fechaPublicacion: '2026-05-01',
    autor: 'Dirección Ejecutiva',
    importante: true,
  },
  {
    id: 'n2',
    titulo: 'Actualización de Protocolo de Seguridad e Higiene',
    contenido: 'Se informa que a partir del 1° de junio entrará en vigencia el nuevo protocolo de seguridad e higiene institucional. Todos los empleados deben completar la capacitación obligatoria disponible en el Portal de RRHH antes del 30 de mayo. Ante consultas, comunicarse con el área de RRHH.',
    categoria: 'comunicado',
    fechaPublicacion: '2026-05-18',
    autor: 'RRHH',
    importante: true,
  },
  {
    id: 'n3',
    titulo: 'Convocatoria: Jornada Institucional 2026',
    contenido: 'Les comunicamos que el próximo 6 de junio se realizará la Jornada Institucional Anual de la Fundación. El encuentro se llevará a cabo en el Auditorio Central a partir de las 9:00 hs. Se realizará una evaluación de objetivos del primer semestre y planificación estratégica. Asistencia obligatoria para todo el personal.',
    categoria: 'evento',
    fechaPublicacion: '2026-05-15',
    autor: 'Dirección Ejecutiva',
    importante: false,
  },
  {
    id: 'n4',
    titulo: 'Nuevos beneficios para el personal',
    contenido: 'Con satisfacción informamos la incorporación de nuevos beneficios para el personal de la Fundación: descuentos en farmacias adheridas, acceso a plataforma de capacitación online y cobertura de anteojos. Más información disponible en el Portal de RRHH o consultando al área de Recursos Humanos.',
    categoria: 'novedad',
    fechaPublicacion: '2026-05-12',
    autor: 'RRHH',
    importante: false,
  },
  {
    id: 'n5',
    titulo: '¡Cumpleaños de Ana Rodríguez!',
    contenido: 'Hoy celebramos el cumpleaños de nuestra querida compañera Ana Rodríguez del sector Administración. ¡Muchas felicidades Ana! Que este nuevo año esté lleno de logros y alegrías.',
    categoria: 'cumpleanos',
    fechaPublicacion: '2026-05-20',
    autor: 'RRHH',
    importante: false,
  },
  {
    id: 'n6',
    titulo: 'Recordatorio: Cierre de presentación de horas extras',
    contenido: 'Se recuerda que el plazo para presentar las planillas de horas extras correspondientes al mes de abril vence el próximo viernes 24 de mayo. Presentar en formato digital al correo administracion@fno.org.ar con el asunto "Horas Extras Abril 2026 - Nombre y Apellido".',
    categoria: 'alerta',
    fechaPublicacion: '2026-05-19',
    autor: 'Administración',
    importante: true,
  },
]

export const eventos: Evento[] = [
  { id: 'e1', titulo: 'Cumpleaños Ana Rodríguez', fecha: '2026-05-20', tipo: 'cumpleanos', empleadoId: '4' },
  { id: 'e2', titulo: 'Jornada Institucional 2026', fecha: '2026-06-06', tipo: 'evento', descripcion: 'Auditorio Central, 9:00 hs.' },
  { id: 'e3', titulo: 'Vencimiento presentación horas extras', fecha: '2026-05-24', tipo: 'vencimiento', descripcion: 'Cierre de planillas abril' },
  { id: 'e4', titulo: 'Cumpleaños Juan Pérez', fecha: '2026-07-10', tipo: 'cumpleanos', empleadoId: '3' },
  { id: 'e5', titulo: 'Feriado Nacional - Día de la Bandera', fecha: '2026-06-20', tipo: 'feriado' },
  { id: 'e6', titulo: 'Capacitación Seguridad e Higiene', fecha: '2026-05-30', tipo: 'evento', descripcion: 'Obligatoria para todo el personal' },
  { id: 'e7', titulo: 'Cumpleaños Carlos Martínez', fecha: '2026-04-18', tipo: 'cumpleanos', empleadoId: '5' },
]

export const tickets: Ticket[] = [
  {
    id: 't1', empleadoId: '2', tipo: 'certificado_laboral',
    asunto: 'Solicitud de certificado de trabajo',
    descripcion: 'Necesito un certificado de trabajo para presentar ante una entidad bancaria para tramitar un préstamo hipotecario.',
    estado: 'resuelto', fechaCreacion: '2026-05-10', fechaActualizacion: '2026-05-12',
    respuesta: 'El certificado ha sido generado y está disponible para retirar en el área de RRHH o puede solicitarlo por email.',
  },
  {
    id: 't2', empleadoId: '3', tipo: 'actualizacion_datos',
    asunto: 'Actualización de número de teléfono',
    descripcion: 'Mi número de teléfono cambió. El nuevo es 299-5001234. Por favor actualizar en el sistema.',
    estado: 'resuelto', fechaCreacion: '2026-05-08', fechaActualizacion: '2026-05-09',
    respuesta: 'Datos actualizados correctamente en el sistema.',
  },
  {
    id: 't3', empleadoId: '5', tipo: 'consulta',
    asunto: 'Consulta sobre vacaciones proporcionales',
    descripcion: 'Quisiera saber cuántos días de vacaciones me corresponden en proporción a mi tiempo trabajado este año.',
    estado: 'en_proceso', fechaCreacion: '2026-05-18', fechaActualizacion: '2026-05-19',
    respuesta: 'Estamos calculando los días proporcionales. Te responderemos a la brevedad.',
  },
  {
    id: 't4', empleadoId: '8', tipo: 'reclamo',
    asunto: 'Diferencia en liquidación de marzo',
    descripcion: 'Observé una diferencia en el monto de mi recibo de sueldo de marzo en comparación con lo acordado. Solicito revisión.',
    estado: 'abierto', fechaCreacion: '2026-05-20', fechaActualizacion: '2026-05-20',
  },
]

export const estadisticasMensuales = [
  { mes: 'Ene', empleados: 9, ausencias: 3, solicitudes: 5 },
  { mes: 'Feb', empleados: 9, ausencias: 2, solicitudes: 4 },
  { mes: 'Mar', empleados: 10, ausencias: 4, solicitudes: 7 },
  { mes: 'Abr', empleados: 10, ausencias: 3, solicitudes: 6 },
  { mes: 'May', empleados: 10, ausencias: 2, solicitudes: 7 },
]

export const empleadosPorSector = SECTORES.map(sector => ({
  sector: sector.split(' ')[0],
  cantidad: empleados.filter(e => e.sector === sector).length,
})).filter(s => s.cantidad > 0)
